In [55]:
import numpy as np
import pandas as pd
from scipy.stats import skew,kurtosis

In [59]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.append(B)
print(A)

None


In [24]:
iden_m = np.identity(3)

In [25]:
print(iden_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
fuel_data = pd.read_csv('fuel_ferc1.txt')

In [61]:
fuel_data.columns

Index(['record_id', 'utility_id_ferc1', 'report_year', 'plant_name_ferc1',
       'fuel_type_code_pudl', 'fuel_unit', 'fuel_qty_burned',
       'fuel_mmbtu_per_unit', 'fuel_cost_per_unit_burned',
       'fuel_cost_per_unit_delivered', 'fuel_cost_per_mmbtu'],
      dtype='object')

In [30]:
fuel_data.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [62]:
std_fuel_mmbtu_per_unit = np.std(fuel_data['fuel_mmbtu_per_unit'])
print(std_fuel_mmbtu_per_unit)

10.600040781504145


In [32]:
np.percentile(fuel_data['fuel_mmbtu_per_unit'],75)

17.006

In [66]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [38]:
180.00/len(fuel_data)

0.00609694136774718

In [42]:
fuel_cost_per_unit_burned_1994 = sum(fuel_data[(fuel_data['report_year']==1994)&(fuel_data['fuel_type_code_pudl']=='coal') ]['fuel_cost_per_unit_burned'])
fuel_cost_per_unit_burned_1998 = sum(fuel_data[(fuel_data['report_year']==1998)&(fuel_data['fuel_type_code_pudl']=='coal') ]['fuel_cost_per_unit_burned'])

In [43]:
((fuel_cost_per_unit_burned_1994 - fuel_cost_per_unit_burned_1998)/fuel_cost_per_unit_burned_1994) *100

20.56765451826049

In [48]:
fuel_data.groupby('report_year')['fuel_cost_per_unit_delivered'].mean()

report_year
1994       63.636060
1995       32.735269
1996     9196.705948
1997    11140.197239
1998      287.154420
1999       25.551627
2000      985.362877
2001       60.050396
2002       47.594361
2003       55.663493
2004      139.524275
2005       41.438184
2006       38.657484
2007       43.325023
2008       58.588197
2009      652.694163
2010       91.862105
2011       59.774667
2012       60.994502
2013      172.307591
2014      192.737183
2015      326.535511
2016      103.901761
2017       46.196861
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64

In [67]:
skew_fuel_qty_burned = skew(fuel_data['fuel_qty_burned'])
print(skew_fuel_qty_burned)

15.850690077422112


In [68]:
kurtosis_fuel_qty_burned = kurtosis(fuel_data['fuel_qty_burned'])
print(kurtosis_fuel_qty_burned)

651.2589365474387
